name: her_highness_salon
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.0.0
  syncfusion_flutter_calendar: ^23.1.36
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  sizer: ^2.0.15
  image_picker: ^1.0.4
  uuid: ^4.1.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  carousel_slider: ^4.0.0
  eva_icons_flutter: ^3.1.0
  otp_text_field: ^1.1.2
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^9.2.0
  google_maps_flutter: ^2.1.1

  # flutter_lints: ^1.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/WhatsApp Image 2023-09-21 at 4.11.42 PM.jpeg"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
